---
title: "Guidelines_and_Conventions v0.1"
author: "GabriellUtt"
date: "2024-11-12"
output: 
  bookdown::html_document2:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Standard Setup R and RStudio

This chapter outlines standard (technical) Setup/Methods contributors working on this project should follow or 
understand

## R/Rstudio System Language

Language should be English. Here are some ways to set the language to English in specific areas:
(*simplify if possible, not sure if best methods...*)

### Set System Language using code
Set the R System language to English using the command ```Sys.setenv(LANG = "en")```. This sets the language preference 
in the system environment variable `LANG`to English. The `LANG`environment variable controls the default language used
for messages, warnings, and errors in R. It seems tso be necessary to also set the locale to English, using the command
```Sys.setlocale("LC_ALL", "en_US.UTF-8")``` to avoid problems, for example with ```styler```.

### Rconsole file

The `Rconsole`file is an R-specific configuration file, to be found on Windows systems under
`r file.path("..", "R", "R-d.d.d", "etc", "Rconsole")`.

Setting `language = EN` inside the file **Rconsole** sets the R system language to English when starting R.

### .Renviron file

*add later how to manage settings using .Renviron file on general or user level*

[Managin R with .Rprofile, .Renviron, ...](https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf)

## R Renv - Manage Dependencies

To avoid complications arising from contributors using different versions of R packages, the `renv` package is used
to create reproducible environments for this R Project.

Short introductions can be found here:

<https://rstudio.github.io/renv/articles/renv.html>
or here
<https://www.appsilon.com/post/renv-how-to-manage-dependencies-in-r#what-is-renv>

The basic workflow is the following:

* to initialise, call renv::init() --> adds project library, lockfile and project R profile
* to update the lockfile, call renv::snapshot() --> updates the lockfile
* to reproduce environment, call renv:restore() --> uses metadata from lockfile
* to update libraries, use renv::update() --> get latest versions of all dependencies

Once libraries are updated, test existing code before proceeding

* use renv::restore() if you don't get project to work with updated libraries
* otherwise: use renv::snapshot() to save new library versions to lockfile

Caveats are:

* renv does not secure a common R version, the Pandoc package (for rmarkdown) and (operating) system
* package installation may fail if binary for that package is no longer available

Further Comments:

* the .gitignore file in the renv subdirectory overrides the main .gitignorefile (only for the renv directory)

# Style Guidelines

The `tidyverse` style guide is used for R code in this project. This [site](https://style.tidyverse.org/) describes the 
style used. The elements (or their interpretations) considered to be most important are listed here:

* load all packages required for a file at the very beginning of a file
* use __snake_case__ for object names
* _add more if necessary..._

Using lintr will help you to get acquainted with the tidyverse style.

## lintr

lintr provides static code analysis for R. It checks for adherence to a given style, identifying syntax errors and 
possible semantic issues, then reports them to you so you can take action

`lintr` is complementary to the `styler` package which automatically restyles code, eliminating 
some of the problems that `lintr` can detect

Here are a few excerpts from the `lintr.rmd` vignette of the `lintr`package which can be opened using the command

```
vignette("lintr", package = "lintr")
```

### Running `lintr` on a project

Checking an R project for lints can be done with three different functions:

-   Lint a single file using `lint()`:

    ``` r
    lint(filename = "R/bad.R")
    ```

-   Lint a directory using `lint_dir()`:

    ``` r
    lint_dir(path = "R")
    ```

    This will apply `lint()` to all R source files matching the `pattern` argument.
    By default, this means all `.R` files as well as `knitr` formats (e.g. `.Rmd`, `.Rnw`).

    `lint_dir` is vectorized over `path`, so multiple directories can be linted at the same time.

-   Lint all relevant directories of an R package using `lint_package()` 

_not further adressed here..._

### Configuring linters

#### The `.lintr` file
The canonical way to configure R projects and packages for linting is to create a `.lintr` file in 
the project root. This is a file in debian control format (`?read.dcf`), each value of which is 
evaluated as R code by `lintr` when reading the settings.
A minimal `.lintr` file can be generated by running `use_lintr()` in the project directory.

#### The .lintr File Example

Currently, the `.lintr` file sets a 120 character line lengths (in contrast to the tidyverse style guide recommendation
of 80) and adds a number of linters to enforce tidyverse style, like checking for snake_case among other things

``` yaml
linters: linters_with_defaults(
    line_length_linter(120),
    absolute_path_linter(), 	# check for absolute paths
    ...
  )
```

(New) lintr settings can be tested on the file `./misc/test_code_style.R

### Configuring linters

Sometimes there are good reasons to exclude specific lines from linting. Therefore, specific lines can be excluded so
that the corresponding lintr comments donot appear any more when linting the file/directory/etc.

One can use comments in the form of `#no lint` for a single line, or `#nolint start`, `#nolint end` for a line
range, possible followed by a listing of linteres to exclude. It's also possible to provide a list of exlusion 
parameters. More details can be found [here](https://lintr.r-lib.org/reference/exclude.html).

### Running `styler` on a project

[styler](https://www.tidyverse.org/blog/2017/12/styler-1.0.0/) is a source code formatter, to automatically format
R code to a style guide (tidyverse style by default). 

It can also be used as an Addin in RStudio once the `styler` package has been installed.

`styler` solves many style issues automatically that are tedious to correct manually, like spacing conventions, but
will leave issues where there is no clear rule on how to solve (e.g. exceedance of line length) to the developper. 

Not that all `styler` functions except `style_text()` overwrite the source code without creating a backup copy, so
use version control in conjunction with styler

# Work Flow

## Git/Versioning

_things like branch per user story, naming of branches, review process etc._

